name: HomophilyNtwNotebooks_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
dependencies:
  - ipywidgets=7.6
  - jupyterlab=3.0.6
  - jupyterlab-python-file
  - python
  - matplotlib
  - numpy
  - pandas
  - networkx